rvm:
  - 1.9.2
  - 1.9.3
  - 2.0
  - jruby
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/edaa9e7b8d7812636188
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: true      # default: false